#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
run_analysis.py
===============
One-shot runner for the complete Take Over Analysis pipeline (Section IV).

Executes all stages sequentially with timing, error handling, and a final
summary report. Each stage can also be run independently.

Usage:
    # Full pipeline (v3)
    python3 run_analysis.py

    # Skip already-completed stages (resume from stage 3)
    python3 run_analysis.py --start 3

    # Run only one stage
    python3 run_analysis.py --only 1

    # Dry run (show what would execute)
    python3 run_analysis.py --dry

    # Spot-check: run Stage 1 on 100 clips only
    python3 run_analysis.py --only 1 --spot 100

    # Include optional YOLO scene tagging (Stage 1b)
    python3 run_analysis.py --yolo

Stages:
    1   compute_derived_signals_v3.py  → derived_signals_v3.parquet + anomaly_flags.csv
    2   label_scenarios.py             → scenario_labels.csv + analysis_master.csv
    2b  yolo_scene_tagger.py           → yolo_scene_tags.csv (optional, --yolo)
    3   fit_mixed_models.py            → model_results.json + modeling_notes.txt
    4   analysis_figures.py            → 10 figures (PDF+PNG)
    5   generate_latex_section.py      → takeover_analysis.tex
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

# ──────────────────────────────────────────────────────────────────────────────
CODE = Path(__file__).resolve().parent
OUT  = CODE / "stats_output"

STAGES = [
    {
        "id": "1",
        "name": "Compute Derived Signals (v3)",
        "script": "compute_derived_signals_v3.py",
        "output": [OUT / "derived_signals_v3.parquet",
                   OUT / "derived_signals_v3.csv",
                   OUT / "anomaly_flags.csv"],
        "desc": "Resampled TTC/THW/DRAC, jerk, roughness, exposure, stabilization",
        "supports_spot": True,
    },
    {
        "id": "2",
        "name": "Label Scenarios",
        "script": "label_scenarios.py",
        "output": [OUT / "scenario_labels.csv", OUT / "analysis_master.csv"],
        "desc": "9-category taxonomy + multi-flag rules + risk/maneuver scores",
    },
    {
        "id": "2b",
        "name": "YOLO Scene Tagging",
        "script": "yolo_scene_tagger.py",
        "output": [OUT / "yolo_scene_tags.csv"],
        "desc": "YOLOv8 on keyframes of anomalous/ambiguous clips (optional)",
        "optional": True,
    },
    {
        "id": "3",
        "name": "Fit Statistical Models",
        "script": "fit_mixed_models.py",
        "output": [OUT / "model_results.json", OUT / "modeling_notes.txt"],
        "desc": "GEE logistic, LMM, propensity-weighted OEM vs OP comparison",
    },
    {
        "id": "4",
        "name": "Generate Figures",
        "script": "analysis_figures.py",
        "output": [CODE / "paper_figs" / "fig_safety_metrics.pdf"],
        "desc": "10 paper-quality figures (PDF+PNG)",
    },
    {
        "id": "5",
        "name": "Generate LaTeX Section",
        "script": "generate_latex_section.py",
        "output": [OUT / "takeover_analysis.tex"],
        "desc": "\\section{Take Over Analysis} with all computed numbers",
    },
]


def fmt_elapsed(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.1f}s"
    m, s = divmod(seconds, 60)
    if m < 60:
        return f"{int(m)}m {s:.0f}s"
    h, m = divmod(m, 60)
    return f"{int(h)}h {int(m)}m {s:.0f}s"


def check_prerequisites():
    """Verify required input files exist before starting."""
    required = [
        (OUT / "per_clip.csv",          "dataset_statistics.py"),
        (OUT / "engagement_source.csv", "analyze_engagement_source.py"),
    ]
    missing = []
    for path, source in required:
        if not path.exists():
            missing.append((path.name, source))

    if missing:
        print("=" * 60)
        print("  MISSING PREREQUISITES")
        print("=" * 60)
        for name, source in missing:
            print(f"  {name}  (generated by {source})")
        print()
        print("Run the prerequisite scripts first, then re-run this pipeline.")
        sys.exit(1)


def run_stage(stage: dict, python: str, extra_args: list[str] | None = None
              ) -> tuple[bool, float]:
    """Run a single stage. Returns (success, elapsed_seconds)."""
    script = CODE / stage["script"]
    if not script.exists():
        print(f"  ERROR: {script} not found")
        return False, 0.0

    cmd = [python, str(script)]
    if extra_args:
        cmd.extend(extra_args)

    t0 = time.time()
    try:
        result = subprocess.run(
            cmd,
            cwd=str(CODE),
            capture_output=False,     # stream output to terminal
            text=True,
        )
        elapsed = time.time() - t0
        return result.returncode == 0, elapsed
    except KeyboardInterrupt:
        elapsed = time.time() - t0
        print(f"\n  Interrupted after {fmt_elapsed(elapsed)}")
        raise
    except Exception as e:
        elapsed = time.time() - t0
        print(f"  EXCEPTION: {e}")
        return False, elapsed


def main():
    parser = argparse.ArgumentParser(
        description="Run the complete Take Over Analysis pipeline.")
    parser.add_argument("--start", type=str, default="1", metavar="ID",
                        help="Start from stage ID (skip earlier stages)")
    parser.add_argument("--only", type=str, default=None, metavar="ID",
                        help="Run only stage ID")
    parser.add_argument("--dry", action="store_true",
                        help="Dry run: show stages without executing")
    parser.add_argument("--spot", type=int, default=0, metavar="N",
                        help="Spot-check: Stage 1 processes only N clips")
    parser.add_argument("--yolo", action="store_true",
                        help="Include optional YOLO scene tagging (Stage 1b)")
    parser.add_argument("--python", default=sys.executable,
                        help="Python interpreter path")
    args = parser.parse_args()

    # Header
    print()
    print("=" * 60)
    print("  TAKEOVER ANALYSIS PIPELINE (v3)")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    print()

    # Build stage order list (string IDs)
    stage_ids = [s["id"] for s in STAGES]

    # Determine which stages to run
    if args.only is not None:
        stages_to_run = [s for s in STAGES if s["id"] == args.only]
        if not stages_to_run:
            print(f"ERROR: no stage '{args.only}'. Valid: {', '.join(stage_ids)}")
            sys.exit(1)
    else:
        try:
            start_idx = stage_ids.index(args.start)
        except ValueError:
            print(f"ERROR: no stage '{args.start}'. Valid: {', '.join(stage_ids)}")
            sys.exit(1)
        stages_to_run = STAGES[start_idx:]

    # Skip optional stages unless requested
    if not args.yolo:
        stages_to_run = [s for s in stages_to_run if not s.get("optional")]

    # Show plan
    for s in STAGES:
        is_included = s in stages_to_run
        opt = " (optional)" if s.get("optional") else ""
        marker = ">>" if is_included else "  "
        skip_note = " [SKIP: use --yolo]" if s.get("optional") and not is_included else ""
        print(f"  {marker} Stage {s['id']:3s}: {s['name']}{opt}{skip_note}")
        print(f"         {s['desc']}")
    print()

    if args.spot > 0:
        print(f"  Spot-check mode: Stage 1 will process only {args.spot} clips")
        print()

    if args.dry:
        print("  (dry run — nothing executed)")
        return

    # Check prerequisites
    check_prerequisites()

    # Execute
    results = []
    total_t0 = time.time()
    n_stages = len(stages_to_run)

    for i, stage in enumerate(stages_to_run, 1):
        print()
        print("─" * 60)
        print(f"  STAGE {stage['id']} ({i}/{n_stages}): {stage['name']}")
        print(f"  Script: {stage['script']}")
        print("─" * 60)
        print()

        extra = []
        if args.spot > 0 and stage.get("supports_spot"):
            extra = ["--spot", str(args.spot)]

        success, elapsed = run_stage(stage, args.python, extra)
        results.append((stage, success, elapsed))

        if success:
            # Check outputs exist
            outputs_ok = all(p.exists() for p in stage["output"])
            status = "OK" if outputs_ok else "OK (some outputs missing)"
            print(f"\n  Stage {stage['id']} completed in {fmt_elapsed(elapsed)} [{status}]")
        else:
            print(f"\n  Stage {stage['id']} FAILED after {fmt_elapsed(elapsed)}")
            print("  Stopping pipeline. Fix the error above and re-run with:")
            print(f"    python3 run_analysis.py --start {stage['id']}")
            break

    total_elapsed = time.time() - total_t0

    # Summary
    print()
    print("=" * 60)
    print("  PIPELINE SUMMARY")
    print("=" * 60)
    for stage, success, elapsed in results:
        icon = "OK" if success else "FAIL"
        print(f"  [{icon:4s}] Stage {stage['id']:3s}: {stage['name']:35s}  {fmt_elapsed(elapsed):>10s}")
    print(f"  {'─'*58}")
    print(f"  Total elapsed: {fmt_elapsed(total_elapsed)}")
    print()

    # List generated files
    all_ok = all(s for _, s, _ in results)
    if all_ok:
        print("  Generated outputs:")
        for stage, _, _ in results:
            for p in stage["output"]:
                if p.exists():
                    size = p.stat().st_size
                    if size > 1024 * 1024:
                        sz = f"{size / 1024 / 1024:.1f} MB"
                    elif size > 1024:
                        sz = f"{size / 1024:.0f} KB"
                    else:
                        sz = f"{size} B"
                    print(f"    {p.relative_to(CODE)}  ({sz})")
        print()
        print("  All stages completed successfully.")
    else:
        n_ok = sum(1 for _, s, _ in results if s)
        print(f"\n  {n_ok}/{len(results)} stages completed. See errors above.")


if __name__ == "__main__":
    main()
